import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />

        <script type="text/javascript">
          let _paq = (window._paq = window._paq || []); // tracker methods
          like"setCustomDimension" should be called before "trackPageView"
          _paq.push(["trackPageView"]); _paq.push(["enableLinkTracking"]); let
          u= "https://nextjsdl2je093qblacknumberthreevercelapp.matomo.cloud/";
          _paq.push(["setTrackerUrl", u + "matomo.php"]);
          _paq.push(["setSiteId", "1"]); let d = document, g
          =d.createElement("script"), s = d.getElementsByTagName("script")[0];
          g.type = "text/javascript"; g.async = true; g.src =
          "//cdn.matomo.cloud/nextjsdl2je093qblacknumberthreevercelapp.matomo.cloud/matomo.js";
          s.parentNode.insertBefore(g, s)
        </script>
      </Head>

      <button onClick={() => alert("hello")}>hello world</button>
    </div>
  );
}
